// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.1 DO NOT EDIT.
package api

import (
	"encoding/json"
	"time"

	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Booking Бронирование, созданное гостем
type Booking struct {
	CreatedAt   time.Time `json:"createdAt"`
	EndTime     time.Time `json:"endTime"`
	EventTypeId string    `json:"eventTypeId"`
	GuestEmail  string    `json:"guestEmail"`
	GuestName   string    `json:"guestName"`
	Id          string    `json:"id"`
	StartTime   time.Time `json:"startTime"`
}

// CreateBookingRequest Запрос на создание брони (endTime вычисляется сервером)
type CreateBookingRequest struct {
	EventTypeId string    `json:"eventTypeId"`
	GuestEmail  string    `json:"guestEmail"`
	GuestName   string    `json:"guestName"`
	StartTime   time.Time `json:"startTime"`
}

// CreateEventTypeRequest Запрос на создание/обновление типа события
type CreateEventTypeRequest struct {
	Description string `json:"description"`
	Duration    int32  `json:"duration"`
	Title       string `json:"title"`
}

// ErrorResponse Единый формат ошибки
type ErrorResponse struct {
	Code    string `json:"code"`
	Message string `json:"message"`
}

// EventType Тип события, создаваемый владельцем
type EventType struct {
	Description string `json:"description"`
	Duration    int32  `json:"duration"`
	Id          string `json:"id"`
	IsDisabled  bool   `json:"isDisabled"`
	Title       string `json:"title"`
}

// Owner Владелец календаря — единственный предустановленный профиль
type Owner struct {
	Description string `json:"description"`
	Email       string `json:"email"`
	Id          string `json:"id"`
	Name        string `json:"name"`
	TimeZone    string `json:"timeZone"`
}

// Slot Слот 30 минут (endTime = startTime + eventType.duration)
type Slot struct {
	EndTime   time.Time `json:"endTime"`
	IsBusy    bool      `json:"isBusy"`
	StartTime time.Time `json:"startTime"`
}

// AdminEventTypesCreate200JSONResponseBody defines parameters for AdminEventTypesCreate.
type AdminEventTypesCreate200JSONResponseBody struct {
	union json.RawMessage
}

// AdminEventTypeByIdUpdate200JSONResponseBody defines parameters for AdminEventTypeByIdUpdate.
type AdminEventTypeByIdUpdate200JSONResponseBody struct {
	union json.RawMessage
}

// AdminOwnerGet200JSONResponseBody defines parameters for AdminOwnerGet.
type AdminOwnerGet200JSONResponseBody struct {
	union json.RawMessage
}

// AdminOwnerUpdate200JSONResponseBody defines parameters for AdminOwnerUpdate.
type AdminOwnerUpdate200JSONResponseBody struct {
	union json.RawMessage
}

// GuestBookingsCreate200JSONResponseBody defines parameters for GuestBookingsCreate.
type GuestBookingsCreate200JSONResponseBody struct {
	union json.RawMessage
}

// GuestSlotsListParams defines parameters for GuestSlotsList.
type GuestSlotsListParams struct {
	Date openapi_types.Date `form:"date" json:"date"`
}

// GuestSlotsList200JSONResponseBody0 defines parameters for GuestSlotsList.
type GuestSlotsList200JSONResponseBody0 = []Slot

// GuestSlotsList200JSONResponseBody defines parameters for GuestSlotsList.
type GuestSlotsList200JSONResponseBody struct {
	union json.RawMessage
}

// AdminEventTypesCreateJSONRequestBody defines body for AdminEventTypesCreate for application/json ContentType.
type AdminEventTypesCreateJSONRequestBody = CreateEventTypeRequest

// AdminEventTypeByIdUpdateJSONRequestBody defines body for AdminEventTypeByIdUpdate for application/json ContentType.
type AdminEventTypeByIdUpdateJSONRequestBody = CreateEventTypeRequest

// AdminOwnerUpdateJSONRequestBody defines body for AdminOwnerUpdate for application/json ContentType.
type AdminOwnerUpdateJSONRequestBody = Owner

// GuestBookingsCreateJSONRequestBody defines body for GuestBookingsCreate for application/json ContentType.
type GuestBookingsCreateJSONRequestBody = CreateBookingRequest

// AsEventType returns the union data inside the AdminEventTypesCreate200JSONResponseBody as a EventType
func (t AdminEventTypesCreate200JSONResponseBody) AsEventType() (EventType, error) {
	var body EventType
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromEventType overwrites any union data inside the AdminEventTypesCreate200JSONResponseBody as the provided EventType
func (t *AdminEventTypesCreate200JSONResponseBody) FromEventType(v EventType) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeEventType performs a merge with any union data inside the AdminEventTypesCreate200JSONResponseBody, using the provided EventType
func (t *AdminEventTypesCreate200JSONResponseBody) MergeEventType(v EventType) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsErrorResponse returns the union data inside the AdminEventTypesCreate200JSONResponseBody as a ErrorResponse
func (t AdminEventTypesCreate200JSONResponseBody) AsErrorResponse() (ErrorResponse, error) {
	var body ErrorResponse
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromErrorResponse overwrites any union data inside the AdminEventTypesCreate200JSONResponseBody as the provided ErrorResponse
func (t *AdminEventTypesCreate200JSONResponseBody) FromErrorResponse(v ErrorResponse) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeErrorResponse performs a merge with any union data inside the AdminEventTypesCreate200JSONResponseBody, using the provided ErrorResponse
func (t *AdminEventTypesCreate200JSONResponseBody) MergeErrorResponse(v ErrorResponse) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t AdminEventTypesCreate200JSONResponseBody) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *AdminEventTypesCreate200JSONResponseBody) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// AsEventType returns the union data inside the AdminEventTypeByIdUpdate200JSONResponseBody as a EventType
func (t AdminEventTypeByIdUpdate200JSONResponseBody) AsEventType() (EventType, error) {
	var body EventType
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromEventType overwrites any union data inside the AdminEventTypeByIdUpdate200JSONResponseBody as the provided EventType
func (t *AdminEventTypeByIdUpdate200JSONResponseBody) FromEventType(v EventType) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeEventType performs a merge with any union data inside the AdminEventTypeByIdUpdate200JSONResponseBody, using the provided EventType
func (t *AdminEventTypeByIdUpdate200JSONResponseBody) MergeEventType(v EventType) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsErrorResponse returns the union data inside the AdminEventTypeByIdUpdate200JSONResponseBody as a ErrorResponse
func (t AdminEventTypeByIdUpdate200JSONResponseBody) AsErrorResponse() (ErrorResponse, error) {
	var body ErrorResponse
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromErrorResponse overwrites any union data inside the AdminEventTypeByIdUpdate200JSONResponseBody as the provided ErrorResponse
func (t *AdminEventTypeByIdUpdate200JSONResponseBody) FromErrorResponse(v ErrorResponse) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeErrorResponse performs a merge with any union data inside the AdminEventTypeByIdUpdate200JSONResponseBody, using the provided ErrorResponse
func (t *AdminEventTypeByIdUpdate200JSONResponseBody) MergeErrorResponse(v ErrorResponse) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t AdminEventTypeByIdUpdate200JSONResponseBody) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *AdminEventTypeByIdUpdate200JSONResponseBody) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// AsOwner returns the union data inside the AdminOwnerGet200JSONResponseBody as a Owner
func (t AdminOwnerGet200JSONResponseBody) AsOwner() (Owner, error) {
	var body Owner
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromOwner overwrites any union data inside the AdminOwnerGet200JSONResponseBody as the provided Owner
func (t *AdminOwnerGet200JSONResponseBody) FromOwner(v Owner) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeOwner performs a merge with any union data inside the AdminOwnerGet200JSONResponseBody, using the provided Owner
func (t *AdminOwnerGet200JSONResponseBody) MergeOwner(v Owner) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsErrorResponse returns the union data inside the AdminOwnerGet200JSONResponseBody as a ErrorResponse
func (t AdminOwnerGet200JSONResponseBody) AsErrorResponse() (ErrorResponse, error) {
	var body ErrorResponse
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromErrorResponse overwrites any union data inside the AdminOwnerGet200JSONResponseBody as the provided ErrorResponse
func (t *AdminOwnerGet200JSONResponseBody) FromErrorResponse(v ErrorResponse) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeErrorResponse performs a merge with any union data inside the AdminOwnerGet200JSONResponseBody, using the provided ErrorResponse
func (t *AdminOwnerGet200JSONResponseBody) MergeErrorResponse(v ErrorResponse) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t AdminOwnerGet200JSONResponseBody) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *AdminOwnerGet200JSONResponseBody) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// AsOwner returns the union data inside the AdminOwnerUpdate200JSONResponseBody as a Owner
func (t AdminOwnerUpdate200JSONResponseBody) AsOwner() (Owner, error) {
	var body Owner
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromOwner overwrites any union data inside the AdminOwnerUpdate200JSONResponseBody as the provided Owner
func (t *AdminOwnerUpdate200JSONResponseBody) FromOwner(v Owner) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeOwner performs a merge with any union data inside the AdminOwnerUpdate200JSONResponseBody, using the provided Owner
func (t *AdminOwnerUpdate200JSONResponseBody) MergeOwner(v Owner) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsErrorResponse returns the union data inside the AdminOwnerUpdate200JSONResponseBody as a ErrorResponse
func (t AdminOwnerUpdate200JSONResponseBody) AsErrorResponse() (ErrorResponse, error) {
	var body ErrorResponse
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromErrorResponse overwrites any union data inside the AdminOwnerUpdate200JSONResponseBody as the provided ErrorResponse
func (t *AdminOwnerUpdate200JSONResponseBody) FromErrorResponse(v ErrorResponse) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeErrorResponse performs a merge with any union data inside the AdminOwnerUpdate200JSONResponseBody, using the provided ErrorResponse
func (t *AdminOwnerUpdate200JSONResponseBody) MergeErrorResponse(v ErrorResponse) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t AdminOwnerUpdate200JSONResponseBody) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *AdminOwnerUpdate200JSONResponseBody) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// AsBooking returns the union data inside the GuestBookingsCreate200JSONResponseBody as a Booking
func (t GuestBookingsCreate200JSONResponseBody) AsBooking() (Booking, error) {
	var body Booking
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromBooking overwrites any union data inside the GuestBookingsCreate200JSONResponseBody as the provided Booking
func (t *GuestBookingsCreate200JSONResponseBody) FromBooking(v Booking) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeBooking performs a merge with any union data inside the GuestBookingsCreate200JSONResponseBody, using the provided Booking
func (t *GuestBookingsCreate200JSONResponseBody) MergeBooking(v Booking) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsErrorResponse returns the union data inside the GuestBookingsCreate200JSONResponseBody as a ErrorResponse
func (t GuestBookingsCreate200JSONResponseBody) AsErrorResponse() (ErrorResponse, error) {
	var body ErrorResponse
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromErrorResponse overwrites any union data inside the GuestBookingsCreate200JSONResponseBody as the provided ErrorResponse
func (t *GuestBookingsCreate200JSONResponseBody) FromErrorResponse(v ErrorResponse) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeErrorResponse performs a merge with any union data inside the GuestBookingsCreate200JSONResponseBody, using the provided ErrorResponse
func (t *GuestBookingsCreate200JSONResponseBody) MergeErrorResponse(v ErrorResponse) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t GuestBookingsCreate200JSONResponseBody) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *GuestBookingsCreate200JSONResponseBody) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// AsGuestSlotsList200JSONResponseBody0 returns the union data inside the GuestSlotsList200JSONResponseBody as a GuestSlotsList200JSONResponseBody0
func (t GuestSlotsList200JSONResponseBody) AsGuestSlotsList200JSONResponseBody0() (GuestSlotsList200JSONResponseBody0, error) {
	var body GuestSlotsList200JSONResponseBody0
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromGuestSlotsList200JSONResponseBody0 overwrites any union data inside the GuestSlotsList200JSONResponseBody as the provided GuestSlotsList200JSONResponseBody0
func (t *GuestSlotsList200JSONResponseBody) FromGuestSlotsList200JSONResponseBody0(v GuestSlotsList200JSONResponseBody0) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeGuestSlotsList200JSONResponseBody0 performs a merge with any union data inside the GuestSlotsList200JSONResponseBody, using the provided GuestSlotsList200JSONResponseBody0
func (t *GuestSlotsList200JSONResponseBody) MergeGuestSlotsList200JSONResponseBody0(v GuestSlotsList200JSONResponseBody0) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsErrorResponse returns the union data inside the GuestSlotsList200JSONResponseBody as a ErrorResponse
func (t GuestSlotsList200JSONResponseBody) AsErrorResponse() (ErrorResponse, error) {
	var body ErrorResponse
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromErrorResponse overwrites any union data inside the GuestSlotsList200JSONResponseBody as the provided ErrorResponse
func (t *GuestSlotsList200JSONResponseBody) FromErrorResponse(v ErrorResponse) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeErrorResponse performs a merge with any union data inside the GuestSlotsList200JSONResponseBody, using the provided ErrorResponse
func (t *GuestSlotsList200JSONResponseBody) MergeErrorResponse(v ErrorResponse) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t GuestSlotsList200JSONResponseBody) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *GuestSlotsList200JSONResponseBody) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}
